# Generated by Django 6.0.5 on 2026-05-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
